name: emotion_recognition_webapp

description: Emotion Recognition Web App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  google_fonts: ^4.0.3
  flutter:
    sdk: flutter

  provider: ^6.0.0
  path_provider:
  camera:
  path:
  camera_web: ^0.3.1+2
  cross_file_image: ^1.0.0
  http_parser: ^4.0.2
  http:
  dcdg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets\fonts\TitilliumWeb-Regular.ttf
    - family: SourceCodePro
      fonts:
        - asset: assets\fonts\SourceCodePro-Regular.ttf
  uses-material-design: true
